# Generated by Django 3.1.1 on 2020-10-17 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deputy_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('bill_no', models.IntegerField()),
                ('ex_amount', models.IntegerField()),
                ('sale_tax', models.IntegerField()),
                ('income_tax', models.IntegerField()),
                ('service_tax', models.IntegerField()),
                ('PST_tax', models.IntegerField()),
                ('inclusive_amount', models.IntegerField()),
                ('payment_recieved', models.BooleanField()),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.deputy')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cash', models.DateTimeField(auto_now_add=True)),
                ('recieved_from', models.CharField(max_length=100)),
                ('on_account_of', models.CharField(max_length=100)),
                ('mode_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=10)),
                ('cheque_no', models.IntegerField(blank=True, null=True)),
                ('phone_no', models.IntegerField(blank=True, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.invoice_list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice_list',
            name='description',
            field=models.ManyToManyField(to='main.order'),
        ),
        migrations.AddField(
            model_name='invoice_list',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school'),
        ),
        migrations.AddField(
            model_name='invoice_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
