# Generated by Django 3.1.1 on 2020-10-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_list',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
