# Generated by Django 3.1.1 on 2020-10-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201017_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
    ]
